package fstm.projet.view;

import fstm.projet.controller.Diagnostic_CTR;
import fstm.projet.model.bo.Client;
import fstm.projet.model.bo.Maladie_chronique;
import fstm.projet.model.bo.Region;
import fstm.projet.model.bo.Symptoms;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.util.Vector;

public class Diagonisation extends javax.swing.JFrame {


    /**
     * Creates new form NewJFrame1
     */
    public Diagonisation(fstm.projet.model.bo.Client c, double temp, Region r) {
        myclient = c;
        temperature = temp;
        region = r;
        initComponents();
    }

    public Diagonisation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setBackground(new java.awt.Color(204, 255, 255));

        jScrollPane1.setViewportView(jList1);

        jList2.setBackground(new java.awt.Color(204, 255, 255));

        m = new DefaultListModel<>();
        m2 = new DefaultListModel<>();

        try {
            m.addAll(Diagnostic_CTR.afficheSy());
        } catch (ClassNotFoundException | IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        jList1.setModel(m);
        jList2.setModel(m2);

        jScrollPane2.setViewportView(jList2);

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setText(">>");

        jButton2.setBackground(new java.awt.Color(153, 255, 102));
        jButton2.setText(">");

        jButton3.setBackground(new java.awt.Color(102, 255, 51));
        jButton3.setText("<");

        jButton4.setBackground(new java.awt.Color(51, 153, 255));
        jButton4.setText("<<");

        jButton5.setBackground(new java.awt.Color(51, 255, 0));
        jButton5.setText("Diagoniser");

        jButton6.setBackground(new java.awt.Color(255, 51, 51));
        jButton6.setText("Retour");

        jRadioButton1.setText("Hypertendu");

        jRadioButton2.setText("Cardiaque");

        jRadioButton3.setText("Diabatique");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jScrollPane1)
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane2)
                                .addGap(42, 42, 42))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(206, 206, 206))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jRadioButton1)
                                .addGap(64, 64, 64)
                                .addComponent(jRadioButton2)
                                .addGap(62, 62, 62)
                                .addComponent(jRadioButton3)
                                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane2)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(jButton1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton2)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton3)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButton4)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jRadioButton1)
                                                .addComponent(jRadioButton2))
                                        .addComponent(jRadioButton3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton5)
                                        .addComponent(jButton6))
                                .addGap(29, 29, 29))
        );

        pack();
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jButton3.addActionListener(evt -> jButton3ActionPerformed());
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jButton5.addActionListener(evt -> jButton5ActionPerformed());
        jButton6.addActionListener(e -> {
            setVisible(false);
            new ConsulterDiag(myclient).setVisible(true);
        });


    }// </editor-fold>

    private void jButton5ActionPerformed() {
        Vector<Maladie_chronique> malad = new Vector<>();
        Vector<Symptoms> listSelectionner = new Vector<>();

        for (int i = 0; i < m2.getSize(); i++) {
            listSelectionner.add(m2.getElementAt(i));
        }
        if (jRadioButton1.isSelected()) {
            malad.add(new Maladie_chronique(1, "Hypertendu"));
        }
        if (jRadioButton2.isSelected()) {
            malad.add(new Maladie_chronique(2, "Cardiaque"));
        }
        if (jRadioButton3.isSelected()) {
            malad.add(new Maladie_chronique(3, "diabatique"));
        }

        try {
            Diagnostic_CTR.diagoniser(myclient, listSelectionner, malad, temperature, region);
        } catch (ClassNotFoundException | IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    private void jButton4ActionPerformed(ActionEvent actionEvent) {
        for (int i = 0; i < m2.getSize(); i++) {
            m.addElement(m2.getElementAt(i));
        }
        m2.clear();
    }

    private void jButton3ActionPerformed() {
        for (Symptoms o : jList2.getSelectedValuesList()) {
            m.addElement(o);
        }
        for (int i : jList2.getSelectedIndices()) {
            m2.remove(i);
        }
    }

    private void jButton2ActionPerformed(ActionEvent actionEvent) {
        for (Symptoms o : jList1.getSelectedValuesList()) {
            m2.addElement(o);
        }
        for (int i : jList1.getSelectedIndices()) {
            m.remove(i);
        }
    }

    private void jButton1ActionPerformed(ActionEvent actionEvent) {
        for (int i = 0; i < m.getSize(); i++) {
            m2.addElement(m.getElementAt(i));
        }
        m.clear();
    }

    /**
     */
/*
    public static void main(String args[]) {
        */
    /* Set the Nimbus look and feel *//*

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        */
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     *//*

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagonisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        */
    /* Create and display the form *//*

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {

                new Diagonisation().setVisible(true);
            }
        });
    }
*/

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private JList<Symptoms> jList1;
    private JList<Symptoms> jList2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private Client myclient;
    private Region region;
    private double temperature;
    private DefaultListModel<Symptoms> m;
    DefaultListModel<Symptoms> m2;
    // End of variables declaration
}
